author:
  - Valentin Robert <valentin.robert.42@gmail.com>

copyright: Galois, Inc. 2020

dependencies:
  - ansi-wl-pprint ^>= 0.6
  - base ^>= 4.13
  - bytestring
  - containers ^>= 0.6
  - io-streams
  - lens
  - language-sally ^>= 0.2
  - mtl
  - parameterized-utils ^>= 2.0
  - text
  - what4

description: Generates transition systems from What4 descriptions

ghc-options:
  - -Wall
  - -Werror=incomplete-patterns
  - -Werror=missing-methods
  - -Werror=overlapping-patterns

library:
  exposed-modules:
    - What4.TransitionSystem
  source-dirs: src

license: BSD3

name: what4-transition-system

synopsis: Generates transition systems from What4 descriptions

tests:
  transition-system-tests:
    dependencies:
      - what4-transition-system
    main: TransitionSystemTest.hs
    source-dirs: test

version: 0.0.1.0
