name: What4 CI
on:
  - push
  - pull_request
jobs:
  linux:
    name: Testing ${{ matrix.os }} GHC-${{ matrix.ghc }}
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.allow-failure }}
    strategy:
      matrix:
        os: [ubuntu-18.04]
        ghc: [8.10.3, 8.8.4, 8.6.5]
        allow-failure: [false]
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - uses: cachix/install-nix-action@v12
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - uses: actions/cache@v2
        name: Cache builds
        with:
          path: |
            ${{ steps.setup-haskell.outputs.cabal-store }}
            ~/.cabal/packages
            ~/.cabal/store
            dist-newstyle
          key: |
            cabal-${{ runner.os }}-ghc${{ matrix.ghc }}-${{ github.ref }}
          restore-keys: |
            cabal-${{ runner.os }}-ghc${{ matrix.ghc }}-
      - name: Cabal update
        shell: bash
        run: nix-shell -p cabal-install --run 'cabal update'
      - name: Cabal check
        shell: bash
        run: |
          cd what4
          nix-shell -p cabal-install --run 'cabal check'
      - name: GHC Version
        run: |
          echo GHC=haskell.compiler.ghc$(echo ${{ matrix.ghc }} | sed -e s,\\.,,g) >> $GITHUB_ENV
          echo ZLIB_LOC="$(nix eval --raw nixpkgs.zlib)/lib" >> $GITHUB_ENV
      - name: Cabal configure
        shell: bash
        # Note: the explicit LD_LIBRARY_PATH is needed for GHC 8.6.5
        # which doesn't seem to process the --extra-lib-dirs
        # correctly.  When only GHC 8.8 or later are supported, the
        # LD_LIBRARY_PATH manipulation may be removed for all steps.
        run: |
          cd what4
          nix-shell -p cabal-install $GHC gmp zlib --run 'LD_LIBRARY_PATH="$ZLIB_LOC:$LD_LIBRARY_PATH" cabal configure -fSTPTestDisable -fdRealTestDisable -fsolverTests --extra-lib-dirs="$ZLIB_LOC"'
      - name: Build
        shell: bash
        run: |
          cd what4
          nix-shell -p cabal-install $GHC gmp zlib --run 'LD_LIBRARY_PATH="$ZLIB_LOC:$LD_LIBRARY_PATH" cabal build --extra-lib-dirs="$ZLIB_LOC"'
      - name: Test
        shell: bash
        run: |
          echo Boolector version $(nix eval nixpkgs.boolector.version)
          echo CVC4 version $(nix eval nixpkgs.cvc4.version)
          echo Yices version $(nix eval nixpkgs.yices.version)
          echo Z3 version $(nix eval nixpkgs.z3.version)
          nix-shell -p cabal-install $GHC abc-verifier boolector cvc4 yices z3 --run 'cabal test what4'
      - name: Documentation
        shell: bash
        run: |
          cd what4
          nix-shell -p cabal-install $GHC --run 'LD_LIBRARY_PATH="$ZLIB_LOC:$LD_LIBRARY_PATH" cabal haddock what4 --extra-lib-dirs="$ZLIB_LOC"'
